### ISSUE TITLE
Expand form to include all fields in the "mega app" prototype

### ISSUE THREAD

**Issue by sarahfathallah** [codefordc/districthousing#119]
Based on this form: http://www.formstack.com/forms/?1721573-qkkmpdNPHb
The html file can also be downloaded here: https://dl.dropboxusercontent.com/u/36727215/form.html

NB: Some fields might not appear/show up as there's some kind of conditional logic behind, so it's better to play around with the form to see those or look at the code.

**Comment by kevko** [comment]
Closing out as not current.
