### ISSUE TITLE
Create New Applicant is not smooth -

### ISSUE THREAD

**Issue by jposi** [codefordc/districthousing#151]
When you create a new applicant, the screens go:
enter name
and then the output is a screen that says lots of information is missing and then you have to hit edit.

That doesn't feel super smooth to me. Why doesn't it just take you to the edit.

![screen shot 2014-11-25 at 7 40 49 pm](https://cloud.githubusercontent.com/assets/3505071/5194438/ff07c03a-74da-11e4-9b25-925910dc9e40.png)

**Comment by jrunningen** [comment]
Buttons to add/remove income sources on the onboarding page seems a bit too in-depth for the onboarding page, and more like something that should be implemented in the income section of the main form.  So, I'm going to close this issue, and save the income updates for #179.
