### ISSUE TITLE
Support applications whose length grow with the number of household members (e.g. Samuel Kelsey)

### ISSUE THREAD

**Issue by emanuelfeld** [codefordc/districthousing#153]
Pages 11-15 of the Samuel Kelsey application need to be filled out by each member of the household. This will require either creating a new PDF that has these pages already duplicated a certain number of times or having a new set of these pages added for each new household member added in the web form.

**Comment by kevko** [comment]
That situation is unique enough that we are not supporting this kind of feature in the current app. Too hard to generalize. Each application will require a little custom work, and unfortunately Samuel Kelsey may involve a lot.
