### ISSUE TITLE
Create dropdown for Gender field

### ISSUE THREAD

**Issue by sarahfathallah** [codefordc/districthousing#165]
Male / Female, to avoid data entry errors.

Not sure how to treat non-binary genders, but Stacey didn't either when I asked.

**Comment by evonfriedland** [comment]
@jrunningen this should be closed as well

**Comment by jrunningen** [comment]
At the risk of being exclusionary, this issue is closed.

**Comment by evonfriedland** [comment]
There's a blank in the the gender drop down so that it can be filled on paper for other options
