### ISSUE TITLE
Create dropdowns for relevant fields

### ISSUE THREAD

**Issue by sarahfathallah** [codefordc/districthousing#166]
Similary to #165, create dropdown options to select whenever possible. This applies to:

- Race
- Ethnicity
- Nationality
- State of birth (should be able to select none if Country of birth is not the US)
- Driver license state

(See Formstack mock-up for the detailed options under each one: http://www.formstack.com/forms/?1721573-qkkmpdNPHb , should be pretty straightforward)

**Comment by evonfriedland** [comment]
@jrunningen this should have been closed with #214

**Comment by jrunningen** [comment]
Right you are.
