### ISSUE TITLE
Unclear household member headings

### ISSUE THREAD

**Issue by sarahfathallah** [codefordc/districthousing#168]
When you fill out info for a household member, is it possible to have headings like "Household member 1", "Household member 2", etc.? (Would be even ideal once information is saved to replace those headings with the name of the person).

As of now it's unclear when you start filling out that there's a second page coming. When you hit the button "Next" after filling out the first one, it just looks like the information got deleted. (Not sure if this makes sense?).

**Comment by evonfriedland** [comment]
@lizhaney this is fixed, right?

**Comment by lizhaney** [comment]
I like the change to Client. And the list thing is super cool! I might add a # to spur the understanding that you can click on it. It would be helpful to have a count of HHmembers..

Eg. Household Members (1) after you've entered 1 and are working on the 2nd.

Otherwise looks great!

**Comment by evonfriedland** [comment]
@lizhaney @jrunningen how should we visually distinguish the counts from the percentages (also need to see if we can fix the spillover)
![image](https://cloud.githubusercontent.com/assets/4269640/6098385/8191799c-afaa-11e4-956a-cdad1080463d.png)
