### ISSUE TITLE
Current residence doesn't need "End date"

### ISSUE THREAD

**Issue by sarahfathallah** [codefordc/districthousing#170]
There's a nice little tooltip that comes up when you don't fill it out properly too :)

**Comment by jrunningen** [comment]
I pitched this question to the Slack channel just now:

> question for everyone: how should the user indicate that a residence is the current residence?  option 1: click a "this is my current residence" checkbox that disables the "end date" field.  option 2: we relabel the "end date" field to "end date or lease end date", and if the users sets this to a future date, we consider that residence to be a current residence.

I have implemented solution 1, though I am open to arguments for solution 2.
