### ISSUE TITLE
The View Unrecognized Fields

### ISSUE THREAD

**Issue by lizhaney** [codefordc/districthousing#171]
Found a variety of unrecognized fields, some issues more concerning than others.
1. Several fields that are in the Field Name Dictionary aren't being recognized.
2. Wacky variants of fields don't seem to have been added to the code... ala Tick Yeses, Reason for moving Addressses
3. Can't find the Disability field listed
4. Need a way to track personal references // list them

These fields aren't recognized:
PROPERTY < Can't find naming convention of field for Proprerty applying for
GenderMaleTickYes <-- Need to be added to code?
GenderFemaleTickYes <-- Need to be added to code?
CoheadName<-- Needs to be changed for "Spouse's Name"
AddressStateInitial <-- Need to be added to code
MarriedTickYes <-- Should be recognized.. in FND
SeparatedTickYes <--Needs to be added to code?
SingleTickYes<--Needs to be added to code?
LL1AddressCity<-- Should be recognized .. in FND
LL1AddressZip<--- Should be recognized.. in FND
AddressLeaseExpDate <--- Should be recognized.. in FND
EvictY <--Nuanced field "for a lease violation"
EvictN <-- Nuanced field "for a lease violation"
LL1AddressStreet <--- Should be recognized.. in FND
DivorcedTickYes <--Needs to be added to code?
MaidenName <--Needs to be added to code?
DisabilityY <-- No Idea what this is
DisabilityN <-- No Idea what this is
AddressStart <--- Should be recognized.. in FND
AddressEnd <--- Should be recognized.. in FND
LL1AddressState<--- Should be recognized.. in FND
AddressReasonForMoving <--Needs to be added to code?
Address2Phone <--Needs to be added to code? Home phones are very 90's?
Address2Start <--- Should be recognized.. in FND
Address2End <--- Should be recognized.. in FND
Address3Phone<--Needs to be added to code? Home phones are very 90's?
Address3Start <--- Should be recognized.. in FND
Address3End <--- Should be recognized.. in FND
LL2AddressStreet <--- Should be recognized.. in FND
LL2AddressCity<--- Should be recognized.. in FND
LL2AddressState<--- Should be recognized.. in FND
LL2AddressZip<--- Should be recognized.. in FND
LL2AddressPhone<--Needs to be added to code? Home phones are very 90's?
Address2ReasonForMoving<--Needs to be added to code? Home phones are very 90's?
LL3AddressStreet <--- Should be recognized.. in FND
LL3AddressCity <--- Should be recognized.. in FND
LL3AddressState <--- Should be recognized.. in FND
LL3AddressZip <--- Should be recognized.. in FND
LL3AddressPhone<--Needs to be added to code? Home phones are very 90's?
Address3ReasonForMoving<--Needs to be added to code?
Contact1Name  <- Need a way to track personal references
Contact2Name <- Need a way to track personal references
Contact2Address <- Need a way to track personal references
Contact1Phone <- Need a way to track personal references
Contact2Phone <- Need a way to track personal references

**Comment by evonfriedland** [comment]
@lizhaney those LL addresses aren't being recognized because we currently use the LL#Mail convention for person addresses (e.g. LL1MailCity rather than LL1AddressCity)

**Comment by evonfriedland** [comment]
All of these have new been fixed, excepting:

PROPERTY < Can't find naming convention of field for Proprerty applying for
CoheadName<-- Needs to be changed for "Spouse's Name"
EvictN <-- Nuanced field "for a lease violation"
MaidenName <--Needs to be added to code?
DisabilityY <-- No Idea what this is
DisabilityN <-- No Idea what this is
Contact2Name <- Need a way to track personal references
Contact2Address <- Need a way to track personal references
Contact1Phone <- Need a way to track personal references
Contact2Phone <- Need a way to track personal references
AddressStateInitial <-- Need to be added to code

**Comment by kevko** [comment]
I think we've fixed most if not all of these. Closing for now, and we'll work back from current pdfs and current data.
