### ISSUE TITLE
Entering other members of Household

### ISSUE THREAD

**Issue by lizhaney** [codefordc/districthousing#175]
I started by *accidentally* entering the wrong number of people in the household.
![image](https://cloud.githubusercontent.com/assets/8462602/5387364/45b848c4-808e-11e4-9791-d005480ab41d.png)
I then had to "Save and Continue" to try and get through to the next step.. three times!
![image](https://cloud.githubusercontent.com/assets/8462602/5387370/64e1fd76-808e-11e4-8569-ebe1acd2fe54.png)

I ended up with 3 blank household members.
![image](https://cloud.githubusercontent.com/assets/8462602/5387373/6e0bc012-808e-11e4-9d24-1605ae96f7e9.png)

Because there were actually only 2 people in my household:
![image](https://cloud.githubusercontent.com/assets/8462602/5387388/a18de1c2-808e-11e4-8195-09ed411d940b.png)

Maybe it'd be easier to have to enter all of their names first to make it more real? What's their name to get situated? Then what're their details?

**Comment by jrunningen** [comment]
Each "Household member" block on the applicant overview page (http://districthousing.runningen.net/applicants/1) has a "Delete" button, which you can use to get rid of unwanted household members, but it sounds like that's not easy enough to find.

Should the household members edit page (AKA http://districthousing.runningen.net/household_members/1/edit) also have a button for removing the household member?  Maybe that would make it more obvious.
