### ISSUE TITLE
Allow a case worker to search for a client in their Salesforce database from the application

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#185]
Bread for the City has a couple of thousand clients in their production database.  We'll need to provide a way for a case worker to quickly pull-up a client's information into the app.

We'll want to verify how case workers find clients (e.g., by name, an identifier).

We'll want to check if the salesforce gem we're using (databasedotcom) supports this type of querying.

**Comment by kevko** [comment]
Salesforce is v2. We will figure out the mechanics at a future date.
