### ISSUE TITLE
Gender Dictionary Update

### ISSUE THREAD

**Issue by minhchaudinh** [codefordc/districthousing#187]
Can we please update the Field Name Dictionary with the following fields:
(1) GenderMaleTickYes 
(2) GenderFemaleTickYes

Currently, "Gender" is the variable, and it is described as Male or Female (M or F). However, we are seeing applications that have a check box.

**Comment by evonfriedland** [comment]
Do some applications only allow male or female? What's our take on that?

**Comment by minhchaudinh** [comment]
Thanks for your note. All applications I have worked on only allow for male/female responses. I have not heard an "official" take on this.

Following the code for dc conduct and the space we all honor there: in an ideal world, we would leave gender as a text box and not a dropbox, tick box, etc. because we recognize a gender spectrum and want to ensure that people feel comfortable.

That being said, the housing applications do *not* have a gender free-text box, and we have to map the pdfs we are given if we want to make applying to Section 8 housing less burdensome in the current system. Your thoughts to improve this are welcomed and appreciated.

**Comment by evonfriedland** [comment]
No problem. I don't have any particular knowledge about this issue. I was just curious and thought it an interesting question re: what happens when Code for DC's official policy interfaces with less welcoming systems. Maybe a worthwhile conversation to have with the Code for DC leadership and others in the affordable housing project group. @mlouie @mattbailey0 @justgrimes @leahbannon

**Comment by sarahfathallah** [comment]
In practice the forms all only have male/female. We've raised the issue with Stacey before for non-binary, and her response was while it might be good to do it, if you can't translate that into the answers format in the form, then that's ground for not accepting the application.

**Comment by evonfriedland** [comment]
Interesting. Thanks, Sarah. I wonder if it's legal to reject applications for that reason. I've heard of some weird gender issues when it comes to admission to homeless shelters. Have we encountered any similar concerns with regard to this project?

**Comment by sarahfathallah** [comment]
They don't reject applications for not filling out the gender fields in a certain way, but they do if applications have empty fields (which would be the case if the gender field on the application is not an open text field, e.g. male/female check mark, tickbox or whatnot).

**Comment by evonfriedland** [comment]
Got it.

**Comment by mattbailey0** [comment]
FWIW I 100% love that this conversation happened.

**Comment by evonfriedland** [comment]
@mattbailey0 is there any guideline on such conflicts with official Code for DC/America policy?

**Comment by mattbailey0** [comment]
Short answer: no.  The idea would be to consult with leadership and figure
out how to proceed.  In this case, although I completely share your concern
around gender binaries, I'm not sure I see a conflict per se.  Exploring
options with the client for a more appropriate approach and then delivering
within larger systemic constraints (exactly what was done here) is probably
the only viable approach.  That then puts us in a stronger position to
continue to advocate for change moving forward.
