### ISSUE TITLE
Use Salesforce IDs to reference applicants rather than internal app IDs

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#190]
Spoke with Bread today.  They sometimes reference clients by their Salesforce IDs.  They thought there might be cases where they want to pull-up a client's housing application in our app using the Salesforce ID.  

For example,
- They could provide a link in Salesforce to our app that automatically pulls up the client's info
- They could manually type in the URL to a client based on a client record in SF.

**Comment by kevko** [comment]
Salesforce is v2. We will figure out the mechanics at a future date.
