### ISSUE TITLE
Stop searching buttons in datatables

### ISSUE THREAD

**Issue by jrunningen** [codefordc/districthousing#192]
In the client selector window, the button text is being included in the search.  Change it so it doesn't include the button text.

![datatables](https://cloud.githubusercontent.com/assets/1123795/5791463/1bcbdd16-9ea5-11e4-93c2-980b6b83cb15.PNG)

**Comment by evonfriedland** [comment]
@jrunningen @mlouie this appears fixed, correct?

**Comment by jrunningen** [comment]
This is still an issue.  Notice how if you type "salesforce" into the search box, everyone is still included.  It's because of the button space that either says "Update from Salesforce" or "Not from Salesforce".  That text shouldn't be part of the search corpus.
