### ISSUE TITLE
Change Race field in Demographic section to be drop-down

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#198]
As a case worker, I expect the possible values for Race to match the possible values that appear in the printed application forms.  
- The text input field should be a drop-down
- The drop down should contain only the values for Race that appear on the printed forms.

![screen shot 2015-01-28 at 11 15 30 am](https://cloud.githubusercontent.com/assets/1302023/5941517/81022892-a6df-11e4-94f0-f9feba6b51d0.png)

**Comment by jrunningen** [comment]
Interesting, so multiple races are possible.  We'll have to update the database schema to support that.

**Comment by mlouie** [comment]
Stacey says that most of the time  people just select one.  She said we can keep this as a dropdown and then if someone feels strongly that they need to select another race they can mark it with a pen after the application is printed.

**Comment by jrunningen** [comment]
Okay, we can keep it simple, in that case.
