### ISSUE TITLE
Make the first residence in Residence History represent the Current Residence

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#200]
The first residence in Residence History should be explicitly called out to be the client's "Current Residence."  
- The End Date for the Current Residence should always read, "Present"

**Comment by jrunningen** [comment]
#170 suggests that End Date should be interchangeable with Lease End Date, instead of saying "Present."  What say you to this?

**Comment by jrunningen** [comment]
Rolling with this solution for now.
