### ISSUE TITLE
UI - Add Main Edit Button

### ISSUE THREAD

**Issue by jposi** [codefordc/districthousing#203]
Might make sense to have a big edit button up top so that you can click edit to edit any field, rather than go through by segment
![screen shot 2015-01-28 at 8 39 17 pm](https://cloud.githubusercontent.com/assets/3505071/5950890/e48967a6-a72d-11e4-9429-c5b77c003b6d.png)

**Comment by jrunningen** [comment]
I don't think I follow.  Can you elaborate on how you see this working?

**Comment by kevko** [comment]
I agree the 'I want to edit this' flow could be improved. But I think letting people edit any field within the applicant overview screen would take a lot of work. 

I'm closing for now, we can revisit if problems show up in user testing.
