### ISSUE TITLE
Change options for Marital Status

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#210]
Stacey wants to make the following changes to the list of options for Marital Status:
- Change "Never Married" to "Single"
- Add "Separated"

@jrunningen: Besides changing the values in the dropdown boxes, is there anything else we need to do to handle in terms of outputting to the PDF?

**Comment by jrunningen** [comment]
There's a lot of work left to be done for adding working field names.  It's fairly simple work, but there are lots of fields.

**Comment by evonfriedland** [comment]
@jrunningen this should be closed, right?

**Comment by jrunningen** [comment]
Yes.
