### ISSUE TITLE
NoMethodError in Applicants#show

### ISSUE THREAD

**Issue by terrycDC** [codefordc/districthousing#220]
Received the following error when clicking "Select Client" on the districthousing.org homepage.

NoMethodError in Applicants#show
Showing /home/jrunning/districthousing/app/views/applicants/show.html.erb where line #98 raised:

undefined method `interval' for #<Income:0x000000031d70b0>
Extracted source (around line #98):
95
96
97
98
99
100
101
          
            <%= number_to_currency(income.amount) %>
          </td>
          <td>
            <%= income.interval %>
          </td>
          <td>
            <%= income.source %>

Rails.root: /home/jrunning/districthousing

Application Trace | Framework Trace | Full Trace
app/views/applicants/show.html.erb:98:in `block in _app_views_applicants_show_html_erb__1106361515713071601_87754840'
app/views/applicants/show.html.erb:89:in `_app_views_applicants_show_html_erb__1106361515713071601_87754840'
Request

Parameters:

{"id"=>"101"}
Toggle session dump
Toggle env dump
Response

Headers:

None

![image](https://cloud.githubusercontent.com/assets/6002123/6095358/1c993d8c-af27-11e4-83a3-1e5d3c59946c.png)

**Comment by jrunningen** [comment]
My fault.  I pushed a commit without adding the migration file first.  Fixed now.

**Comment by terrycDC** [comment]
No problem, glad to catch these things quick! 

--Sent from my mobile device.
