### ISSUE TITLE
Make index styling pretty

### ISSUE THREAD

**Issue by emanuelfeld** [codefordc/districthousing#223]
Total number in the tabs has the same styling as % completion.
Index number on the view isn't styled and should appear consistent across views.

**Comment by kevko** [comment]
Here's a somewhat dramatic idea for styling the index number. 
Currently it looks like this:
![screen shot 2015-02-25 at 8 23 53 pm](https://cloud.githubusercontent.com/assets/578345/6384772/09f570c2-bd2f-11e4-89b7-c48f7e940d07.png)
What does that (1) mean, really? Instead it could be:
![terribly-hacky-mockup](https://cloud.githubusercontent.com/assets/578345/6384782/4bf3873e-bd2f-11e4-8d94-105a8e344c67.png)
Not sure if creating a new header will increase clarity or confusion. But I think could make it more obvious that the progress bar is associated with the current entity, not the entire form -- a problem we've talked about before. 

Practical steps for doing this: The index number is currently generated by (<%=@model.my_number%>) in each edit.html.erb for each tab's "view." That needs a div in each file for styling. Then possibly switch its location with the progress bar if we decide we like that.

Feedback most welcome before I dive in to try to do this.

**Comment by jposi** [comment]
I like this, but I don't think it's a must have. BFC can totally deploy without it. They've dealt with worse. :-)

**Comment by emanuelfeld** [comment]
This has been fixed
