### ISSUE TITLE
Priority Fields colored/indicated in Field Name Dictionary

### ISSUE THREAD

**Issue by lizhaney** [codefordc/districthousing#230]
Can you update the field name dictionary with icons or a color to indicate they're "priority"?

lizhaney [8:05 PM]
Terry wrote down which EXACT fields are priority (woohoo) but it seems like having the field name dictionary as the place to go is best..  

Eg. We have following as "priority categorie"  so could you star/color the fields within these in the FND:
Household information (names of others living in unit)
Race/Ethnicity
Date of birth/age
Relationship to applicant
Rental history (landlords, cost of rent, reason for moving, etc.)

https://docs.google.com/spreadsheets/d/1hP6V-fKwUONUma8PuXgmNxLH3EABJtn_SjqB68F_p1Y/edit#gid=154382166

**Comment by jrunningen** [comment]
We're going to consider everything in the Field Name Dictionary as a priority field, ready for use.
