### ISSUE TITLE
Proposed Field Name, Cohead prefix

### ISSUE THREAD

**Issue by trycrmr** [codefordc/districthousing#236]
Proposed Field Name
Cohead prefix
Details
This prefix would represent the details of a cohead of the applicant's household. Use is similar to HH. Another possible workaround is HH1 could default to the cohead of the household. An example of the cohead to a household would be an applicant's spouse.

**Comment by terrycDC** [comment]
Could be used in Channel Square Apartments.

**Comment by kevko** [comment]
This is not on Bread's worksheet, so I'm presuming it's fairly rare -- enough to not make it a priority right now.
