### ISSUE TITLE
Fix applicant navigation tabs

### ISSUE THREAD

**Issue by emanuelfeld** [codefordc/districthousing#247]
![image](https://cloud.githubusercontent.com/assets/4269640/6383785/6f5cdfa2-bd22-11e4-9278-1d723381e5cd.png)
They're all bunched now that Contacts was added (and more to come), plus the # indexing.

**Comment by jmezetin** [comment]
If you will be adding more tabs, it may help to stack the tabs vertically. 
Here's an example: http://jsfiddle.net/MgcDU/8940/
