### ISSUE TITLE
Criminal History - Crime Type Other

### ISSUE THREAD

**Issue by bigyehooda** [codefordc/districthousing#262]
Add the option "Other" as a choice for crime type, and/or add more choices such as misdemeanor, simple assault, etc.

**Comment by evonfriedland** [comment]
Is there a full list somewhere

**Comment by bigyehooda** [comment]
That would be a question for Stacey.I think for now, the best would to add Misdemeanor (which I guess should be an option itself?) and simple assault and also an "Other" option. You could also just add other and call it a day.

**Comment by evonfriedland** [comment]
@jrunningen I meant to close this with #286

**Comment by emanuelfeld** [comment]
@mlouie this is fixed
