### ISSUE TITLE
Change valid values of Citizenship

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#266]
On the Client and Household Member forms, when asking about Citizenship, provide 3 choices consistent with the applications, 
- US Citizen
- Non-Citizen with eligible immigration status
- Other

**Comment by evonfriedland** [comment]
So not the country drop down we currently have?

**Comment by emanuelfeld** [comment]
@mlouie am I correct above?

**Comment by mlouie** [comment]
Closing this.  It looks like we resolved it.

![screen shot 2015-07-08 at 7 43 00 pm](https://cloud.githubusercontent.com/assets/1302023/8584905/9e40cdb6-25a9-11e5-9df3-3dde83220e73.png)
