### ISSUE TITLE
Add Driver's License Expiration Date

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#270]
When asking for a Driver's License, also ask for the Driver's License Expiration Date.

**Comment by emanuelfeld** [comment]
Doing this

**Comment by emanuelfeld** [comment]
A note that #237 is the same issue

**Comment by mlouie** [comment]
It looks like we've already fixed this.

![screen shot 2015-11-16 at 8 50 20 pm](https://cloud.githubusercontent.com/assets/1302023/11200380/bb1f3c36-8ca3-11e5-8782-e9cbb5513f3d.png)

The field is in our database as well.  Hat tip to @charleshuang80.
