### ISSUE TITLE
New Field - Medical Insurance Information

### ISSUE THREAD

**Issue by bigyehooda** [codefordc/districthousing#271]
Stacey has asked for the following fields related to medical insurance:
- Primary Insurance, ID#, Monthly Payment, Address
- Secondary Insurance, ID#, Monthly Payment, Address

**Comment by evonfriedland** [comment]
Would this go on the person page or in another view

**Comment by bigyehooda** [comment]
This also wasn't specified. I would assume main client page.

**Comment by kevko** [comment]
Stacey says lets just not include this. Not common enough, too much hassle.
