### ISSUE TITLE
.pdf Samuel Kelsey: Page 2 Address

### ISSUE THREAD

**Issue by jposi** [codefordc/districthousing#277]
Not sure if this is related to issue https://github.com/codefordc/districthousing/issues/275 but the current address and previous address are inaccurate as well.

Where it says "current", it actually maps to the address of the landlord of the last previous residence. "previous landlord" maps to the 2nd most recent previous landlord. (in order of: current, previous, 2nd previous)
![image](https://cloud.githubusercontent.com/assets/3505071/6384652/7d797630-bd2d-11e4-9081-10886dfbaafa.png)

**Comment by jposi** [comment]
this is still a problem.

**Comment by sarahfathallah** [comment]
Priority

**Comment by thadk** [comment]
I think I fixed this. http://districthousing.org:3000/housing_forms/285

 LL1NName => LL1Name

**Comment by mlouie** [comment]
Confirmed fixed! Thank you, @thadk!
