### ISSUE TITLE
New Fields - Type of Contact (Emergency v Personal Reference)

### ISSUE THREAD

**Issue by bigyehooda** [codefordc/districthousing#278]
Stacey has asked to add to the contact tab a field to designate whether the contact is an emergency contact or a personal reference.

NOTE: In Marcus' note from his meeting with Stacey, there is something along the lines of "Ability to note a primary additional contact." Marcus will follow up on what that was supposed to be.

**Comment by sarahfathallah** [comment]
Seems to be high priority because it dictates where in the PDF the info will be printed, no?

**Comment by mlouie** [comment]
This appears to be fixed.

![screen shot 2015-11-16 at 8 52 44 pm](https://cloud.githubusercontent.com/assets/1302023/11200413/081ec57e-8ca4-11e5-9046-9318f7ad56db.png)

This is our database.  Another hat tip goes to @charleshuang80.
