### ISSUE TITLE
.pdf Samuel Kelsey: Page 3 Income

### ISSUE THREAD

**Issue by jposi** [codefordc/districthousing#281]
Excludes income listed first. Also, oddly, makes them lowercase.

![image](https://cloud.githubusercontent.com/assets/3505071/6384712/2ed6d724-bd2e-11e4-9c14-e76bcbe13644.png)

**Comment by sarahfathallah** [comment]
Priority

**Comment by jeffgruber** [comment]
Me!

**Comment by jeffgruber** [comment]
Not me!

**Comment by thadk** [comment]
"Excludes income listed first" -- this isn't clear to me: 
I thought maybe Source and Type were different but in the dictionary they seem similar:
```
IncomeSource	Source/type of the first income listed in a form
```

**Comment by lizhaney** [comment]
I updated this so Applicant is listed First. I coded the type and incomebyhh in the picture.

![image](https://cloud.githubusercontent.com/assets/8462602/9483210/1aab0fb0-4b6b-11e5-8c73-ea09b451716b.png)

**Comment by ursulakaczmarek** [comment]
Field names should be updated to reflect income field names in dictionary, e.g.:
Income1Source
Income2Amount
Income3EarnerName

**Comment by mlouie** [comment]
Changed field names according to field guide.  Thank you, @ursulakaczmarek!!!

![screen shot 2016-12-07 at 7 24 18 pm](https://cloud.githubusercontent.com/assets/1302023/20992562/d2c8d41a-bcb2-11e6-8272-0f045aa0603d.png)
