### ISSUE TITLE
Label the client's 'Current Residence' on Residence History tab

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#282]
As a caseworker, when I click on the Residence History tab, I want to know which address is the client's 'Current Residence.'  
- The client's current residence should be labeled when a user click on the Residence History tab

![screen shot 2015-02-25 at 8 41 15 pm](https://cloud.githubusercontent.com/assets/1302023/6384788/8ba9ec06-bd2f-11e4-9c00-fe7de57c0414.png)

**Comment by evonfriedland** [comment]
The app does this already.

![image](https://cloud.githubusercontent.com/assets/4269640/6407434/f1e5d050-be0d-11e4-957d-86449263ee33.png)
