### ISSUE TITLE
Proposed Field Name MaritalStatusX

### ISSUE THREAD

**Issue by marisleyton** [codefordc/districthousing#291]
Proposed Field Name
MaritalStatusX
Details
The form has a checkbox to be filled with M, D, S, L or E. See image.
![maritalstatusx](https://cloud.githubusercontent.com/assets/11639452/6815963/301c6992-d263-11e4-996a-0bd2c226d673.png)

**Comment by emanuelfeld** [comment]
This seems like a pretty unique field structure, so might be better to leave it for people to fill out on paper.
