### ISSUE TITLE
Enable someone to copy Mailing Address to Residence Address

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#302]
Some people's mailing address and residence address are the same.  To make it faster to fill out the form, allow the case worker to click a button to copy information from the mailing address (assumed to be filled out first) to the residence address.

![screen shot 2015-04-10 at 10 50 01 am](https://cloud.githubusercontent.com/assets/1302023/7090215/5e4aae0a-df6f-11e4-8cf8-5caab39fab0a.png)

**Comment by emanuelfeld** [comment]
#174 somewhat related

**Comment by kevko** [comment]
@jrunningen started a branch which would address this (ha, pun!) a while back https://github.com/codefordc/districthousing/tree/copy_current_address

**Comment by jrunningen** [comment]
This is fixed now.  All address fields have a drop down at the bottom that will let you copy a previous address into the address fields
