### ISSUE TITLE
.pdf: Big Field Addition Project (no coding, all .pdf revision)

### ISSUE THREAD

**Issue by jposi** [codefordc/districthousing#308]
Stacey's added fields for every single possible field into her .pdfs, and she likes that. It includes drop downs (eg. how many pets - drop down 1, 2, 3). All of the .pdfs are: https://drive.google.com/drive/u/0/folders/0B-Y7LlHGL0S_b2pCT1pMekxndk0/0B-Y7LlHGL0S_Y1lBLUQtR21FT0E

The big project is to walk through every .pdf and add the fields, unnamed (checkboxes, text boxes, drop downs) to limit the amount of handwriting that SJ et.al have to do.

**Comment by kevko** [comment]
I believe this is out of date, so closing for now.
