### ISSUE TITLE
.pdf: Hedin House. Rental History should start with Current Address / Fill Landlord Info

### ISSUE THREAD

**Issue by LomaxRx** [codefordc/districthousing#310]
Rental History table should start with current address and then fill out previous addresses
Landlord and Address column should fill with landlord's Name and Address, not applicant's address

**Comment by lizhaney** [comment]
This looks correct to me? If someone can clarify I can fix.

![image](https://cloud.githubusercontent.com/assets/8462602/8586374/be3b602e-25bb-11e5-8531-7bc56d154408.png)

**Comment by jrunningen** [comment]
Yes, that looks right to me.
