### ISSUE TITLE
Add referencing prefixes to field name dictionary

### ISSUE THREAD

**Issue by lizhaney** [codefordc/districthousing#323]
I believe when we were working in MLK we talked about coding some of the Income Fields as

**IncomeBySourceType**1Amount

Type being variables like: Wages, Disability, SSI, Child Support, Public Assistance.

I also need functionality like this for Household Members on Congress Park.

Suggested

**HHbyRole1** Name etc.

HHbyAgeAdult

**Comment by emanuelfeld** [comment]
We have Income1Source and Income1Amount. You're talking about aggregating by the Source value?

**Comment by lizhaney** [comment]
Yup

**Comment by kevko** [comment]
Closing (at least for now) as we focus on shipping with our current data model.
