### ISSUE TITLE
Garfield Hills household members are listed incorrectly

### ISSUE THREAD

**Issue by lizhaney** [codefordc/districthousing#324]
Should start w/ Applicant not HH1

**Comment by lizhaney** [comment]
PDF is coded wrong, to Clarify table list look slike

HH1Name [Head] 
HH2Name HH2Relationship

Should be:

Name [Head]
HH1Name HH1 Relationship

**Comment by adinneen** [comment]
@emanuelfeld updated PDF with new names here https://drive.google.com/open?id=0B8rQX6ajIoEMcGg1dEJraHdTbHc. Issue #324 can be closed.
