### ISSUE TITLE
Add new location is broken

### ISSUE THREAD

**Issue by emanuelfeld** [codefordc/districthousing#339]
Redirects you to "/", issues notice that user already signed in, and fails to add new location. @jrunningen

**Comment by jrunningen** [comment]
I actually don't even see the "Add new location" button anymore.  Has it been removed?

**Comment by jrunningen** [comment]
The button to add a housing form was commented out in 5560983c.  Was that intentional?  The ability to upload a PDF and test with it is sort of critical for adding new forms and form fields.

**Comment by emanuelfeld** [comment]
I commented it out, since another add new location button was added to the top navigation bar (the PDF button, though there is likely a better icon for the purpose).

**Comment by emanuelfeld** [comment]
PS, I had edited the location table to be more generic and now only the client pages show the location preview. We might want to add that back to the main location table temporarily.

**Comment by jrunningen** [comment]
Oh, I see.  Bug confirmed.

**Comment by jrunningen** [comment]
I'm guessing that #342 will fix this, because it modifies the housing form edit/create workflow to go back to the way it was, instead of intermediately redirecting users to update_location.js.  Have a look at that, and merge it in if you have no objection.

**Comment by meiao** [comment]
This seems to be fixed. At least I was able to create a new housing on my environment.
