### ISSUE TITLE
Embed Onboarding Form in App

### ISSUE THREAD

**Issue by lizhaney** [codefordc/districthousing#345]
This way ppl will be able to get onboarded to updating PDF's easier. 

iframe>src="https://docs.google.com/forms/d/1gYvzB1NNDYi19OBxPDhe74MMnYemNTwQZZgSZDWs4NU/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe

**Comment by jrunningen** [comment]
Which onboarding form do you mean?

**Comment by lizhaney** [comment]
https://docs.google.com/forms/d/1gYvzB1NNDYi19OBxPDhe74MMnYemNTwQZZgSZDWs4NU/viewform?usp=already_responded

This gathers information, when you complete it, it directs you to another form that's basically a checklist of all the places involved in PDFing, Google Drive, etc etc. Both of these forms are in the onboarding folder in the DH drive. The embed code got messed up in my comment, but I took away the opening/closing brackets so you can see it.

Happy to discuss whether this is relevant, or if instructions should geared towards Stacy's staff are more relevant as we roll it out and they start updating stuff.

**Comment by kevko** [comment]
A good idea, but currently not a priority. We may not be editing any more pdfs or editing them in an entirely different process.
