### ISSUE TITLE
Embed PDFing Tip Sheet on Website

### ISSUE THREAD

**Issue by lizhaney** [codefordc/districthousing#348]
Probably Best in another link below Field Name Dictionary.

Should include content like this gudie: https://docs.google.com/forms/d/1gYvzB1NNDYi19OBxPDhe74MMnYemNTwQZZgSZDWs4NU

**Comment by jrunningen** [comment]
The app has an existing "here's how you make a PDF correctly" page at https://districthousing.org/pdf_guide.

Somewhere along the line, the navbar link to this page seems to have been removed, making it impossible to find if you don't know the URL.

Two things must be done:

1. A link to this page should be re-added to the navbar
2. The content of the page should be checked for consistency with Stacey's instructions at https://docs.google.com/document/d/1VDgHIpfYDwmZHsSxyAzYanTwNbLLyKU1mPRWnZGffk8/edit

In some places, the pdf_guide page and Stacey's doc disagree.  Font sizing is one example.  Where they disagree, Stacey's doc must take preference.  Where Stacey's doc says something that pdf_guide doesn't cover, it must be added to pdf_guide.

**Comment by jrunningen** [comment]
@lizhaney, the form you link to doesn't say much about PDFing tips.  Did you mean to include a different link?

**Comment by kevko** [comment]
Not a priority as most pdf-ing has been done by us or Stacey at this point. If in the future we start adding new pdfs through volunteers, we can revisit how best to document the process.
