### ISSUE TITLE
Field names

### ISSUE THREAD

**Issue by jimwebb** [codefordc/districthousing#350]
Howdy! I'm new to the project, so this may not be what you need, but here are some field names I can't find in the dictionary. These are from the [3 Tree Flats](https://drive.google.com/folderview?id=0B-Y7LlHGL0S_eUp1N3JsUW5xNzA&usp=drive_web&tid=0B-Y7LlHGL0S_b2pCT1pMekxndk0) application:

* Daytime phone (as opposed to work phone)
* Nighttime phone (as opposed to home/cel phone)
* Name of Supervisor (for current and past jobs)
* Annual Income (for current and past jobs)
* Car type
* Car year
* Car license plate
* Car license plate state
* Bank, checking account number, savings account number
* Creditors: name, account number, balance, monthly payment
* Second employer (current employer, not a past employer) and full employer contact information
* Pet Y/N
* Pet kind
* Pet breed/weight
* Have you ever been asked to move from an apartment or evicted by a court because you failed to pay your rent or otherwise violated your lease? Y/N (Second question: If so, explain)
* Number of bedrooms in current housing
* Do you rent or own your current housing (check one)
* If you own your property, do you receive monthly rental income? Y/N
* Check utilities paid by you: Heat / Electricity / Gas / Other (specify)
* Approximate monthly cost of utilities paid by you (excluding phone and cable TV)
* Bedroom size requested (check): Studio / One BR / Two BR / Three BR / Handicap BR
* For each member of the household: marital status, birthdate, age, SSN, Student Y/N
* Do you anticipate any additions to the household in the next 12 months? Y/N
* If so, explain

Plus a *lot* more specific income, real estate, and asset questions in pages 7-13 of the application. Thanks!

**Comment by jrunningen** [comment]
If the app doesn't yet support that field, you can simply give it a sensible name that you choose yourself (try to follow our conventions, at least), and the app will leave it blank when filling the PDF.

Our goal is not to have 100% coverage for every field in every PDF - that's just not realistic.  We'd settle for filling out merely *a whole bunch* of fields in each PDF.
