### ISSUE TITLE
Add testing instruction to README

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/districthousing#353]

**Comment by kevko** [comment]
We currently have instructions for filling in test data. Did you mean that or something else?

Closing the issue for now. Will re-open if still relevant.

**Comment by stvnrlly** [comment]
It was a while ago, so I'm not positive, but I may have been talking about instructions for running the test suite.

**Comment by kevko** [comment]
Ah, that makes more sense and would be nice. But I'm going to leave this closed as we really need to prune our issues list to pressing priorities.
