### ISSUE TITLE
HTTPS configuration issues

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/districthousing#358]
The certificate looks solid, but there are a few issues with the configuration that can cause weird behaviors: https://www.ssllabs.com/ssltest/analyze.html?d=districthousing.org.

**Comment by meiao** [comment]
I just removed some old protocols/ciphers and the qualys grade was upgraded to A-

**Comment by mlouie** [comment]
![screen shot 2016-11-17 at 7 49 18 pm](https://cloud.githubusercontent.com/assets/1302023/20414138/f757c5b6-acfe-11e6-8dac-8dc3caf6b21e.png)
