### ISSUE TITLE
[PDF]: View Page 1: Misc changes

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#363]
From Stacey:

- Top right box is for their office use only-- we can delete those fields.  
- Top left we can fill in Property = "View at Edgewood" and phone is 202-635-1995.
- Size of Unit can be default "1 BR" since that's all they have in the building.
- Current Residency: That first address should be the Mailing Address (it's currently pulling the residence address)
- Phone is not populating (should be the client's primary phone)
- Current Residency dates to and from-- the To could be default "Present" since it's the place the person is currently staying.
- Previous Address: The previous LL's phone number is not populating.

**Comment by link2matt** [comment]
-Deleted Office Use Only fields AM/PM
-Changed Curent Residency field to Mail for Address, City, State, Zip
-Change Property and Tel to text objects, no longer fields
-Change Phone to PreferredPhone
-Ignored Current Date
-Changed Landlord's phone to LL2Phone

**Comment by ursulakaczmarek** [comment]
Verified field cheanges- #closeissue
