### ISSUE TITLE
[PDF]: View Page 2: Misc. changes

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#364]
From Stacey:
- Personal References: they are both showing the same address
- The top address is wrong (phone #s are correct). 
- The sizing is weird.
- Every check box from here down is linked-- checking one checks them ALL.

**Comment by link2matt** [comment]
-Correct Personal Ref. address #1, which was wrongly set to address #2 
-Lowered height on references names
-Preview employer had some fields from employer 1 overlapping--I deleted the employer 1 fields for address, phone, zip

**Comment by link2matt** [comment]
-Made each generic check box and generic text field unique fields--should fix check box issue

**Comment by kevko** [comment]
Verified each issue.

Text for "Position" on Employment is a little small, but probably no way to avoid that with this form. I believe sizing is no longer weird.
