### ISSUE TITLE
[PDF]: View Page 4: Misc. changes

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#366]
From Stacey:
- How Did You Hear About Us: Default can have "Other" checked and list Bread for the City.
- Just under that is the criminal question-- that's not populating, either.

**Comment by link2matt** [comment]
Added Bread for the City as pre-populated in How Did You Hear About Us

Criminal History data doesn't seem to work for this PDF's fields

**Comment by ostermanj** [comment]
Changed first criminal history response to CrimeDescription field. Fields for others don't seem to exist (Evicted for drugs, sex offender).

**Comment by NealHumphrey** [comment]
For the How did you hear -as of 9/1/16 this is not populating (used Andre_Goodwin)
