### ISSUE TITLE
[PDF]: View Page 5: Remove all fields from this page

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#368]
From Stacey:

" We can remove all fields on this page-- they are all either signature or office use only fields."

**Comment by link2matt** [comment]
All fields deleted.

**Comment by ursulakaczmarek** [comment]
Verified detetion- #closeissue

**Comment by NealHumphrey** [comment]
Verified deletion - OK to close
Verified for Andre_Goodwin and 'View' property

**Comment by mlouie** [comment]
Thank you, @NealHumphrey!
