### ISSUE TITLE
[PDF]: View Page 7: The contact person and all of their information is missing.

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#369]
From Stacey:
- The contact person and all of their information is missing.  
- And we can remove the field that asks for signature.

**Comment by link2matt** [comment]
Added Contact person fields
Removed signature fields

***Note-- There was a blank page 6.  I deleted the blank page.

**Comment by ursulakaczmarek** [comment]
Verified changes- #closeissue

**Comment by NealHumphrey** [comment]
I verified for Andre_Goodwin and the 'View' property - contact person and all their info is coming in. This was on page 6 (due to the deleted blank page noted above)
