### ISSUE TITLE
[PDF] Samuel Kelsey page 7: name missing and no language default

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#375]
From Stacey:
- Applicant's name at the top is not populating.
- Also, can we have "English" checked by default?

**Comment by wrightcolinb** [comment]
- Changed Fields "FName" and "LName" to "FirstName" and "LastName"
- "English" was already set to be checked by default, no change.

**Comment by br-mcdermott** [comment]
checking  Housing--Samuel Kelsey for Andre_Goodwin& Beverly Cummings  1) Name is showing at top.  2) English is **not** checked by default

**Comment by mlouie** [comment]
Modifed the PDF to have the checkbox marked by default.  I had to remove the checkbox form element and replace it with a text field with an 'X.'  I did actually try to use an emoji checkbox, but the text field was not having any of that.  Le sigh.  We'll see if this is suitable for now.
