### ISSUE TITLE
[PDF] Samuel Kelsey page 11: name missing and nationality mismatch

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#377]
From Stacey: 
- Name is not populating.
- Nationality should be the country of birth, not necessarily citizenship.
- Can the check boxes be pre-populated with citizen information?

**Comment by wrightcolinb** [comment]
- Changed "FName" and "LName" to "FirstName" and "LastName"
- Changed "Nationality" to "CountryOfBirth"
- First checkbox prepopulated through "USCitizenTickYes", others not changed

**Comment by mlouie** [comment]
Confirmed resolved.
