### ISSUE TITLE
[PDF] Samuel Kelsey page 13: name missing, date needs default, race box

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#378]
From Stacey:
- Name is not populating. It should be the applicant's name in both places.
- The date should be default to "today".
- Race and Ethnicity boxes are not checked.

**Comment by wrightcolinb** [comment]
- Changed "FName" and "LName" in both locations to "FirstName" and "LastName"
- No field for today's date currently, may need to add. No change made.
- Updated race and ethnicity boxes with the Race___YesNo fields and Ethnicity___YesNo fields
