### ISSUE TITLE
[PDF] Samuel Kelsey page 15 and 21: blank 

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#379]
From Stacey:
- Not populated at all.

Oops. What happened?

**Comment by wrightcolinb** [comment]
- Page 15 Populated
- Page 21 Name Populated

**Comment by br-mcdermott** [comment]
Page 15 Populated 
Page 21 Name only populated

**Comment by mlouie** [comment]
Confirmed resolved.
