### ISSUE TITLE
[PDF] Dupont Park page 2: Populate references with people who are tagged as 'Reference' and not 'Emergency'

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#380]
From Stacey:
- The references can't be people who are related to the applicant. Maybe only use the ones tagged as "reference" and not "emergency".
- The city/state/zip is not populating.

**Comment by ostermanj** [comment]
For the emergency/reference issue I think the only data field in play is Contact, which doesn't  distinguish between relatives and nonrelatives. More of a date model issue?
