### ISSUE TITLE
[PDF] Dupont Park page 3: various income issues

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#381]
From Stacey:
- Income not populated fully. Need Income source, and income per (mo/wk/yr).
- The annual income box needs to be made smaller -- stuff typed in there is HUGE.
- Can that annual income field be auto-calculated?

**Comment by wrightcolinb** [comment]
Changed Income source to populate now, monthly income should have worked already (no change)
Resized annual income boxes, and changed them to auto-populate

**Comment by mlouie** [comment]
Verified that the first two income sources populate correctly.  Thank you!

We'll still need to fix the third income source on page 4, but we're allllllmost there.

**Comment by ostermanj** [comment]
Changed pg 4 income source to Income3Source. Should work, but populating is not yet verified

**Comment by mlouie** [comment]
Verified @ostermanj's fix. Excellent!

Also, fixed the annual amount by renaming the field to 'Income3AmountYearly.'  Was originally 'Income3AmountAnnual.'

**Comment by NealHumphrey** [comment]
Doing verification checks - this does not seem to be working still.

- "per" fields are not populating. 
- 'average annual income' on page 4 (the 3rd type) still not populating

Using the Annie Schamberger user and also checked Beverly Cummings

Autocalculate - 
for Beverly Cummings, website says 956 weekly; pdf says $3,824 ('per' field is blank) and annual sum field in pdf is $49,712. Autocalculate is $3,824 is the same as 4 weeks, so this is sort of correct, but from the PDF view it's wrong - monthly * 12 != annual.
