### ISSUE TITLE
[PDF] Dupont Park page 9: student status missing, etc

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#383]
From Stacey:

- Fields for Student Status are missing. 
- Also, the last field where it asks you to explain any "Yes" answers -- can we make that a multi-line field so it looks better when you type in it?

**Comment by mlouie** [comment]
- StudentStatus was used to filled out whether a student was full-time or not.  This may might not be a sufficient solution as it will print out a value, "Full-time," "Part-time," or "Not a student."  We may need to add a field that indicates whether someone is a full-time student or not, e.g., "FullTimeStudentYesNo."
- The last field on this page was changed to a multi-line.  In Acrobat, the lines breaks corresponded nicely to the printed lines in the PDF.
