### ISSUE TITLE
[PDF] Dupont Park page 10: current and previous address problems

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#384]
From Stacey:
- For the current address, can the "To" date default to "present"?
- Present and Previous Addresses: Reasons for Leaving and LL's addresses are not populating.

**Comment by wrightcolinb** [comment]
Changed so LL mailing addresses populate
Other issues not addressed

**Comment by ostermanj** [comment]
Changed Reason for Leaving fields to be suffixed 1-5.
added "present" as default value for "to" field
whether it populates correctly not tested
