### ISSUE TITLE
[PDF] Dupont Park page 16-17: change defaults

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#385]
From Stacey:
- Remove all fields in the "Initials" boxes, and in the signature field on p 17.
- How did you hear about us? Default answer= Bread for the City on p17.

**Comment by wrightcolinb** [comment]
Removed all initials fields and signature field
Put BftC as default

**Comment by ostermanj** [comment]
Verified

**Comment by kevko** [comment]
I see initials removed, and a field for 'How did you hear about us' but BftC not printing in the box.
