### ISSUE TITLE
[PDF] Samuel Kelsey page 3: income details needed in chart

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#386]
From Stacey: 

- The chart at the bottom should list the income sources and annual amounts.

**Comment by wrightcolinb** [comment]
- Populated first column with Name fields (unclear from form if this should instead be a number?)
- Populated Second Column with __IncomeSource
- Populated Third Column with __IncomeAmountYearly

**Comment by ursulakaczmarek** [comment]
Verified income source and annual amounts  populated- #closeissue
