### ISSUE TITLE
[PDF] Samuel Kelsey page 5: criminal history missing check box, text box too small

### ISSUE THREAD

**Issue by kevko** [codefordc/districthousing#387]
From Stacey:
- Conviction check box is not populating.  
- Can we extend the text box to be the same size as the line? (I was unable to fit "Possession of an illegal substance, 2001, DC" in there).

**Comment by wrightcolinb** [comment]
- No field for a Conviction TickYes type, no change made
- Text box extended to fill line

**Comment by ostermanj** [comment]
Verified

**Comment by mlouie** [comment]
We would need to add a ConvictionTickYes field, likely based off of information we collect about crimes that have been committed.  Closing this -- we need to collect more requirements from Stacey if this is an issue she wants fixed.
