### ISSUE TITLE
Applicant Overview - Map does not work

### ISSUE THREAD

**Issue by meiao** [codefordc/districthousing#393]
In the applicant overview screen, clicking on the maker icon, instead of showing up the map nothing happens.

**Comment by jrunningen** [comment]
I merged your change. The site should update automatically pretty soon. Please check on it to confirm the fix.

**Comment by meiao** [comment]
I navigated for some time on the site.
Map is working. But I had some trouble viewing the PDFs in the Locations page.
Will check on that later.
